server.port=8081

app.db.url=${DB_URL:jdbc:mysql://localhost:3306/peopledb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
app.db.username=${DB_USERNAME:root}
app.db.password=${DB_PASSWORD:root}
app.db.ddl-auto=${DB_DDL_AUTO:create}
app.db.show-sql=${DB_SHOW_SQL:true}
app.db.pool-size=${DB_POOL_SIZE:10}
