app.datasource.url=jdbc:mysql://127.0.0.1:3306/archunit
app.datasource.username=root
app.datasource.password=pass
app.datasource.pool-size=10

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
