server.port=8081
spring.application.name=java-25-spring-ai-2-structured-outputs
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
management.endpoints.web.exposure.include=health
